# Generated by Django 6.1.1 on 2026-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_long_description_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=list, help_text="Dynamic specifications list e.g. [{'label': 'Pieces', 'value': '500'}]", null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, help_text='Full detailed description of the product.', null=True),
        ),
    ]
