# Generated by Django 6.1.1 on 2026-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='SEO alt text for this image. Leave blank to auto-generate from product title.', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first.'),
        ),
    ]
