# Generated by Django 6.1.1 on 2026-09-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('sslcommerz', 'SSLCommerz'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('bank', 'Bank Transfer'), ('other', 'Other')], max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_icons/')),
                ('is_active', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
                ('api_key', models.CharField(blank=True, help_text='API Key / Merchant ID', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='API Secret / Password', max_length=500)),
                ('sandbox_mode', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, help_text='Additional gateway-specific JSON config', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kidurabd', max_length=100)),
                ('site_tagline', models.CharField(blank=True, max_length=200)),
                ('site_email', models.EmailField(blank=True, max_length=254)),
                ('site_phone', models.CharField(blank=True, max_length=30)),
                ('site_address', models.TextField(blank=True)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('currency', models.CharField(choices=[('BDT', '৳  Bangladeshi Taka (BDT)'), ('USD', '$  US Dollar (USD)'), ('EUR', '€  Euro (EUR)'), ('GBP', '£  British Pound (GBP)')], default='BDT', max_length=10)),
                ('currency_symbol', models.CharField(default='৳', max_length=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Min order for free shipping (0 = always charged)', max_digits=10)),
                ('default_shipping_charge', models.DecimalField(decimal_places=2, default=60, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage (e.g. 5 for 5%)', max_digits=5)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_msg', models.TextField(blank=True, default='We are currently performing maintenance. Please check back soon.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
