# Generated by Django 6.1.1 on 2026-09-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link_url', models.CharField(blank=True, default='/', max_length=500)),
                ('link_text', models.CharField(blank=True, max_length=80)),
                ('position', models.CharField(choices=[('home_top', 'Homepage — Top (full width)'), ('home_mid', 'Homepage — Middle Section'), ('home_bottom', 'Homepage — Bottom Section'), ('category_top', 'Category Page — Top'), ('product_top', 'Product Listing — Top'), ('sidebar', 'Sidebar Widget'), ('popup', 'Popup Banner')], default='home_top', max_length=30)),
                ('size', models.CharField(choices=[('full', 'Full Width'), ('half', 'Half Width (2-column)'), ('third', 'One-Third Width (3-column)')], default='full', max_length=10)),
                ('badge_text', models.CharField(blank=True, max_length=30)),
                ('badge_color', models.CharField(blank=True, choices=[('sky', 'Sky Blue'), ('rose', 'Rose / Red'), ('emerald', 'Emerald / Green'), ('amber', 'Amber / Yellow'), ('violet', 'Violet / Purple')], default='sky', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, help_text='Leave empty to show immediately', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave empty to show indefinitely', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['position', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(help_text='Recommended: 1920×700px', upload_to='slider/')),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=60)),
                ('button_url', models.CharField(blank=True, default='/', max_length=500)),
                ('button_style', models.CharField(choices=[('primary', 'Primary (Sky Blue)'), ('secondary', 'Secondary (White Outline)'), ('dark', 'Dark')], default='primary', max_length=20)),
                ('text_position', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20)),
                ('overlay_opacity', models.PositiveSmallIntegerField(default=40, help_text='Overlay darkness 0–90 (0 = no overlay, 90 = very dark)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
