# Generated by Django 6.1.1 on 2026-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_activitylog_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL slug, e.g. "privacy-policy" → /page/privacy-policy/', max_length=255, unique=True)),
                ('content', models.TextField(blank=True, help_text='Full page HTML content (supports CKEditor rich text).')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (defaults to page title if empty).', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description.')),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True, help_text='Show a link to this page in the storefront footer.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
